version: "3.0"
services:
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password